package server.controllers;

public class RequestController {

	public enum REQUESTS {
		LOGIN_USER, LOGOUT_USER,
		GET_ALL_CLIENTS, GET_CLIENT_BY_ID, GET_CLIENT_BY_USERNAME,
		GET_ALL_EMPLOYESS, GET_EMPLOYEE_BY_ID, GET_EMPLOYEE_BY_USERNAME,
		GET_ALL_COMPLAINTS, GET_UNSEEN_COMPLAINTS, GET_UNADDRESSED_COMPLAINTS,ADD_NEW_COMPLAINT,
		GET_ALL_SUBSCRIPTION, GET_SUBSCRIPTION_BY_ID,
		GET_ALL_IMAGES, GET_IMAGES_BY_TITLE, GET_IMAGE_BY_ID,
		GET_ALL_LAYERS, GET_LAYER_BY_ID, GET_LAYERS_BY_IMAGEID
	}
	
	
}
